### ISSUE TITLE
Throw error when secret doesn't exist

### ISSUE THREAD

**Issue by carabaestlein** [snowplow/sql-runner#128] opened 2018-06-15 10:44 UTC
If the user's password secret specified in the playbook doesn't exist, the job still completes successfully with the following message: 

```
SUCCESS: 0 queries executed against 1 targets
```

Wouldn't it be better if it throws an error?

**Comment by alexanderdean** [comment] 2018-06-15 21:28
I believe this is a duplicate of #105, will assign into milestone while we verify.

**Comment by carabaestlein** [comment] 2018-06-15 22:33
@alexanderdean yes sorry indeed looks like a duplicate of #105!

**Comment by alexanderdean** [comment] 2018-06-15 22:33
No worries, closing and descheduling!

**Closed by alexanderdean** 2018-06-15 22:33 UTC
