### ISSUE TITLE
Surface error message for incorrect passwords

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/sql-runner#182] opened 2021-04-28 15:20 UTC
Sometimes we will throw `WARNING: No queries to run` rather than a connection error for incorrect or missing password. SQL-runner should return clearer error messages for each error case.

**Comment by adatzer** [comment] 2022-06-28 08:09
The cause was because of the missing error handling from `fillTemplates` and could be reproduced by any value in playbook that may trigger that error, e.g. `:password: {{notSupportedSecretFunc "X"}}`. It was being mostly surfaced for passwords, as this is where template functions are usually used.

Was fixed in v0.10.0 as part of https://github.com/snowplow/sql-runner/commit/6cf2e12ef7a5cc06b5af747c96cb29f0e682fba3
Closing.

**Closed by adatzer** 2022-06-28 08:09 UTC
